import pandas as pd
import numpy as np
import joblib
import tensorflow as tf
from ydata_synthetic.synthesizers.timeseries.timegan.model import TimeGAN
from config import settings
from pydantic import BaseModel, Field

# --- CONFIGURATION MODEL ---
class GenerationConfig(BaseModel):
    """Validates the structure and types of the parameters generated by the LLM crew."""
    location: str
    t_min: float = Field(alias='t_min')
    t_max: float = Field(alias='t_max')
    humidity_base: float = Field(ge=0.0, le=100.0, description="Base humidity as percentage (0-100)")
    inertia: float = Field(default=2.0, ge=1.0, le=4.0)
    noise_scale: float = Field(default=1.0, ge=0.0, le=5.0)
    ac_status: bool = False
    fan_status: bool = False
    rain_status: bool = False
    indoor_status: bool = False
    start_time: str
    end_time: str

# --- THE GENERATOR CLASS ---
class SynthIoTSystem:
    # --- CONSTANTS ---
    SEQUENCE_LENGTH = 120
    ROLLING_WINDOW = 20
    HUMIDITY_TEMP_SENSITIVITY = 20.0
    MIN_HUMIDITY = 5.0
    MAX_HUMIDITY = 100.0
    TIME_FREQ = '30s'

    # Output Column Names
    COL_DATE = 'Date'
    COL_TIME = 'Time'
    COL_TEMP = 'Temperature(F)'
    COL_HUMIDITY = 'Humidity(%)'
    COL_LOCATION = 'Location'

    def __init__(self, model_path: str, scaler_path: str):
        print(f"Loading TimeGAN from {model_path}...")
        try:
            # Force GPU config if available
            gpus = tf.config.list_physical_devices('GPU')
            if gpus:
                try:
                    for gpu in gpus: tf.config.experimental.set_memory_growth(gpu, True)
                except RuntimeError as e: print(e)
            
            self.synthesizer = TimeGAN.load(model_path)
            self.scaler = joblib.load(scaler_path)
            print("✅ Model & Scaler Loaded.")
        except Exception as e:
            print(f"❌ FATAL: Error loading model or scaler from disk: {e}")
            raise e # Fail fast on startup if models can't be loaded

    def _generate_fresh_texture(self, n_points):
        # Generate raw sequences
        n_sequences = (n_points // self.SEQUENCE_LENGTH) + 2
        synth_data = np.array(self.synthesizer.sample(n_sequences))
        
        # Flatten and Inverse Transform
        flat_data = synth_data.reshape(-1, synth_data.shape[2])
        real_data = self.scaler.inverse_transform(flat_data)
        
        # Extract Noise (Residuals from trend) by subtracting a rolling average
        temp_series = pd.Series(real_data[:, 0])
        hum_series = pd.Series(real_data[:, 1])
        
        t_noise = (temp_series - temp_series.rolling(self.ROLLING_WINDOW, center=True).mean()).fillna(0).values
        h_noise = (hum_series - hum_series.rolling(self.ROLLING_WINDOW, center=True).mean()).fillna(0).values
        
        return t_noise[:n_points], h_noise[:n_points]

    def _generate_physics_trend(self, time_index: pd.DatetimeIndex, t_min: float, t_max: float, inertia: float):
        numeric_hours = time_index.hour + (time_index.minute / 60) + (time_index.second / 3600)
        
        # A sine wave models the daily temperature cycle.
        # The 'shift' adjusts the time of the peak temperature. A standard day peaks
        # around 2 PM (hour 14). Inertia adjusts this.
        shift = 6.0 + inertia

        amplitude = (t_max - t_min) / 2
        midpoint = (t_max + t_min) / 2
        
        return midpoint + amplitude * np.sin((2 * np.pi / 24) * (numeric_hours - shift))

    def generate(self, config: GenerationConfig):
        # Setup Time
        time_index = pd.date_range(start=config.start_time, end=config.end_time, freq=self.TIME_FREQ)
        n_points = len(time_index)
        
        # Physics & Noise
        base_temp = self._generate_physics_trend(time_index, config.t_min, config.t_max, config.inertia)
        t_noise, h_noise = self._generate_fresh_texture(n_points)
        
        final_temp = base_temp + (t_noise * config.noise_scale)
        
        # Humidity Logic
        # Normalize temperature to a 0-1 range based on the day's min/max
        norm_temp = (final_temp - config.t_min) / (config.t_max - config.t_min + 1e-6)
        
        hum_base = config.humidity_base
        # If it's raining, ensure humidity is high
        if config.rain_status: hum_base = max(hum_base, 90.0)
        
        # Humidity generally has an inverse relationship with temperature.
        final_hum = hum_base - (norm_temp * self.HUMIDITY_TEMP_SENSITIVITY) + h_noise
        final_hum = np.clip(final_hum, self.MIN_HUMIDITY, self.MAX_HUMIDITY)
        
        # Create DF
        df = pd.DataFrame(index=time_index)
        df[self.COL_DATE] = df.index.strftime('%d-%m-%Y')
        df[self.COL_TIME] = df.index.strftime('%H:%M:%S')
        df[self.COL_TEMP] = np.round(final_temp, 2)
        df[self.COL_HUMIDITY] = np.round(final_hum, 1)
        df[self.COL_LOCATION] = config.location
        
        return df

# Initialize Global Instance
sys_instance = SynthIoTSystem(model_path=settings.MODEL_PATH, scaler_path=settings.SCALER_PATH)