import numpy as np
import pandas as pd
import logging
from pydantic import BaseModel
from AI.agents import run_crew_with_retry
from AI.tools import get_system_instance, GenerationConfig
from fastapi.concurrency import run_in_threadpool

# Setup distinct logger for this module
logger = logging.getLogger("SynthIoT.Modify")


# --- 1. THE DATA MODEL ---
class ModifyRequest(BaseModel):
    start_date: str  # "YYYY-MM-DD HH:MM:SS"
    end_date: str
    time_interval: str = "30s"

    location: str  # e.g. "Chennai, India" — used to give the AI geographic context

    start_temp: float
    start_hum: float
    end_temp: float
    end_hum: float

    smoothing_coefficient: float = 1.0  # Optional. 1.0 = Linear. >1.0 = Ease-In-Out curve
    prompt: str


# --- 2. THE MATH ENGINE (The Bridge) ---
def bridge_series(series: np.ndarray, start_val: float, end_val: float, coef: float = 1.0) -> np.ndarray:
    """
    Warps a generated time-series to fit perfectly between start_val and end_val
    while preserving the internal texture generated by the GAN.
    """
    n = len(series)
    if n == 0:
        return series

    # 1. Calculate the offsets (Difference between AI data and Target data)
    diff_start = start_val - series[0]
    diff_end = end_val - series[-1]

    # 2. Create a weighting vector (0.0 to 1.0)
    weights = np.linspace(0, 1, n)

    # 3. Apply Smoothing Coefficient (Curve the transition)
    if coef != 1.0:
        weights = np.power(weights, coef)

    # 4. Apply the interpolated adjustment
    # Formula: Original[i] + (StartDiff * (1-w)) + (EndDiff * w)
    adjustment = (diff_start * (1 - weights)) + (diff_end * weights)

    return series + adjustment


# --- 3. THE ORCHESTRATOR ---
async def process_modification_logic(request: ModifyRequest) -> pd.DataFrame:
    """
    Orchestrates the entire modification pipeline:
    Calc Rows -> AI Intent -> Generation -> Bridging -> Physics Clamp.
    """
    # A. Calculate exact row count required to fill the gap
    try:
        start_dt = pd.to_datetime(request.start_date)
        end_dt = pd.to_datetime(request.end_date)
        delta = end_dt - start_dt
        interval_seconds = pd.to_timedelta(request.time_interval).total_seconds()

        # Rows = Total Duration / Interval + 1
        row_count = int(delta.total_seconds() / interval_seconds) + 1

        if row_count < 2:
            raise ValueError("Time range too short. Must result in at least 2 rows.")

        logger.info(f"🔧 Gap Analysis: {row_count} rows from {start_dt} to {end_dt}")

    except Exception as e:
        raise ValueError(f"Date Math Error: {e}")

    # B. AI Orchestration
    # We explicitly tell the agent the constraint so it understands the physics scale
    modified_prompt = f"{request.prompt}. Location: {request.location}. Generate exactly {row_count} rows."

    try:
        # Reuse your existing robust retry logic
        crew_output = await run_in_threadpool(run_crew_with_retry, modified_prompt)
        config = crew_output.pydantic

        if not config:
            raise ValueError("AI returned empty config.")

        # HARD OVERRIDE: The gap constraints are immutable
        config.start_time = request.start_date
        config.end_time = request.end_date
        config.row_count = row_count
        config.time_interval = request.time_interval

    except Exception as e:
        logger.warning(f"⚠️ AI Agent skipped in modify ({e}). Using Fallback interpolation.")
        # Fallback: Just generate a standard bridge if AI fails
        config = GenerationConfig(
            location="Interpolation Mode",
            t_min=min(request.start_temp, request.end_temp),
            t_max=max(request.start_temp, request.end_temp),
            humidity_base=50.0,
            start_time=request.start_date,
            row_count=row_count
        )

    # C. Generate Raw Texture
    sys = get_system_instance()
    df = await run_in_threadpool(sys.generate, config)

    # D. Apply The Bridge (Warping)
    raw_temps = df['Temperature(F)'].values
    raw_hums = df['Humidity(%)'].values

    bridged_temps = bridge_series(
        raw_temps,
        request.start_temp,
        request.end_temp,
        request.smoothing_coefficient
    )

    bridged_hums = bridge_series(
        raw_hums,
        request.start_hum,
        request.end_hum,
        request.smoothing_coefficient
    )

    # E. Final Safety Clamps
    # Even after bridging, humidity must obey physics
    bridged_hums = np.clip(bridged_hums, 0.0, 100.0)

    # Update DataFrame
    df['Temperature(F)'] = np.round(bridged_temps, 2)
    df['Humidity(%)'] = np.round(bridged_hums, 1)

    return df
