"""
Stateless HMAC-based Email OTP — no database storage needed.

How it works
────────────
1. OTP is derived as: HMAC-SHA256(OTP_SECRET, email + time_window) → last 6 digits
   where time_window = floor(unix_timestamp / 300)  →  one new OTP every 5 minutes
2. Both the current window and the previous window are accepted (clock-drift tolerance).
3. After the user submits the correct OTP, we issue a short-lived "verification JWT"
   (purpose="email_verify") that the signup endpoint checks before creating the account.
"""

import hmac
import hashlib
import math
import os
import time
import smtplib
import logging
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.image import MIMEImage
from datetime import datetime, timedelta, timezone

import jwt
from fastapi import HTTPException, status

from config import settings

logger = logging.getLogger("SynthIoT")

# ── OTP window (seconds) ──────────────────────────────────────────────────────
OTP_WINDOW_SECONDS = 300  # 5-minute windows

# ── Pre-resized email assets (small PNGs generated by resize_email_assets.py) ─
# These are well under Gmail's 102 KB clip limit.
_ASSETS_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "assets")
_LOGO_EMAIL_PATH = os.path.join(_ASSETS_DIR, "logo_email.png")
_TEXT_EMAIL_PATH = os.path.join(_ASSETS_DIR, "text_email.png")


# ── Helpers ───────────────────────────────────────────────────────────────────

def _compute_otp(email: str, window: int) -> str:
    """Compute a deterministic 6-digit OTP for a given email + time window."""
    message = f"{email.lower().strip()}:{window}"
    digest = hmac.new(
        key=settings.OTP_SECRET.encode("utf-8"),
        msg=message.encode("utf-8"),
        digestmod=hashlib.sha256,
    ).hexdigest()
    otp_int = int(digest[-8:], 16) % 1_000_000
    return str(otp_int).zfill(6)


def _current_window() -> int:
    """Return the current 5-minute time window slot."""
    return math.floor(time.time() / OTP_WINDOW_SECONDS)


# ── Public API ────────────────────────────────────────────────────────────────

def generate_otp(email: str) -> str:
    """Generate the current OTP for the given email address."""
    return _compute_otp(email, _current_window())


def verify_otp(email: str, otp: str) -> bool:
    """
    Verify an OTP against the current and previous time windows.
    Accepts the previous window to tolerate ~5 min of clock drift or sending delay.
    """
    window = _current_window()
    valid_otps = {
        _compute_otp(email, window),
        _compute_otp(email, window - 1),
    }
    return otp in valid_otps


def send_otp_email(email: str, otp: str) -> None:
    """
    Send the OTP to the user via Gmail SMTP (TLS).

    Uses CID (Content-ID) image embedding — the proper way to embed images
    in HTML emails that works in Gmail. Images are attached as MIME parts
    and referenced with cid: scheme in the HTML.

    Raises HTTPException 503 if the SMTP send fails.
    """
    # ── Build the outer message as multipart/related ─────────────────────────
    # multipart/related groups the HTML body with its inline image attachments.
    msg = MIMEMultipart("related")
    msg["Subject"] = "Your SynthIoT Verification Code"
    msg["From"] = settings.SMTP_FROM or settings.SMTP_USER
    msg["To"] = email

    # ── HTML + plain text wrapped in multipart/alternative ───────────────────
    alt = MIMEMultipart("alternative")
    msg.attach(alt)

    plain = (
        f"Your SynthIoT verification code is: {otp}\n\n"
        "This code expires in 5 minutes. Do not share it."
    )
    alt.attach(MIMEText(plain, "plain"))

    html = f"""\
<!DOCTYPE html>
<html>
<body style="margin:0;padding:0;background:#f4f4f4;font-family:Arial,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0"
         style="background:#f4f4f4;padding:32px 0;">
    <tr>
      <td align="center">
        <table width="520" cellpadding="0" cellspacing="0"
               style="background:#fff;border-radius:12px;
                      box-shadow:0 2px 12px rgba(0,0,0,0.10);
                      padding:36px 40px;">

          <!-- ── Brand header: S logo only ── -->
          <tr>
            <td align="center"
                style="padding:24px 0;background:hsl(225,40%,9.8%);border-radius:8px 8px 0 0;">
              <img src="cid:logo_image"
                   alt="SynthIoT"
                   width="64" height="64"
                   style="display:block;height:64px;width:auto;border:0;" />
            </td>
          </tr>

          <!-- ── Divider ── -->
          <tr>
            <td style="border-top:1px solid #eee;padding-bottom:24px;"></td>
          </tr>

          <!-- ── Body text ── -->
          <tr>
            <td style="color:#333;font-size:15px;padding-bottom:16px;">
              Use the code below to verify your email address:
            </td>
          </tr>

          <!-- ── OTP code box ── -->
          <tr>
            <td align="center" style="padding-bottom:24px;">
              <div style="font-size:40px;font-weight:bold;letter-spacing:12px;
                          padding:18px 12px;background:#f0edff;border-radius:8px;
                          color:#6c47ff;text-align:center;">
                {otp}
              </div>
            </td>
          </tr>

          <!-- ── Footer ── -->
          <tr>
            <td style="color:#999;font-size:13px;line-height:1.6;">
              This code expires in <strong style="color:#555;">5 minutes</strong>.<br>
              If you did not request this, you can safely ignore this email.
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>
</body>
</html>"""

    alt.attach(MIMEText(html, "html"))

    # ── Attach images with CID headers ───────────────────────────────────────
    # These match the cid: references in the HTML above.
    with open(_LOGO_EMAIL_PATH, "rb") as f:
        logo_img = MIMEImage(f.read(), _subtype="png")
        logo_img.add_header("Content-ID", "<logo_image>")
        logo_img.add_header("Content-Disposition", "inline", filename="logo.png")
        msg.attach(logo_img)

    # ── Send via Gmail SMTP (TLS) ─────────────────────────────────────────────
    try:
        with smtplib.SMTP(settings.SMTP_HOST, settings.SMTP_PORT) as server:
            server.ehlo()
            server.starttls()
            server.login(settings.SMTP_USER, settings.SMTP_PASSWORD)
            server.sendmail(settings.SMTP_USER, email, msg.as_string())
        logger.info(f"📧 OTP email sent to {email}")
    except smtplib.SMTPException as exc:
        logger.error(f"❌ SMTP error sending OTP to {email}: {exc}")
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Failed to send OTP email. Please try again later.",
        )


# ── Verification JWT (issued after OTP success) ───────────────────────────────

def create_verification_token(email: str) -> str:
    """
    Issue a short-lived JWT that proves the user verified their email.
    This token is passed to POST /auth/signup as `verification_token`.
    """
    expire = datetime.now(timezone.utc) + timedelta(minutes=settings.OTP_EXPIRE_MINUTES)
    payload = {
        "sub": email.lower().strip(),
        "purpose": "email_verify",
        "exp": expire,
        "iat": datetime.now(timezone.utc),
    }
    return jwt.encode(payload, settings.OTP_SECRET, algorithm="HS256")


def verify_verification_token(token: str) -> str:
    """
    Validate the verification token and return the verified email.
    Raises HTTPException 401 if the token is invalid or expired.
    """
    try:
        payload = jwt.decode(token, settings.OTP_SECRET, algorithms=["HS256"])
    except jwt.ExpiredSignatureError:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Verification token has expired. Please request a new OTP.",
        )
    except jwt.InvalidTokenError:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid verification token.",
        )

    if payload.get("purpose") != "email_verify":
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid token purpose.",
        )

    email: str | None = payload.get("sub")
    if not email:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid verification token.",
        )

    return email
